repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        types: [python]
      - id: ruff-format
        name: ruff format
        language: system
        entry: uv run ruff format
        types: [python]
      - id: ruff-check
        name: ruff check --fix
        language: system
        entry: uv run ruff check --fix
        types: [python]
      - id: Cloud formation
        name: cfn-lint
        language: system
        entry: cfn-lint
        files: ^template.*\.yaml$
  # Pre Push
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest # --verbose
        language: system
        stages: [pre-push]
        pass_filenames: false
        always_run: true
